### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by danmt** [robertohuertasm/solana-bootcamp#1]
Ya tienes casi listo el proyecto! Falta solo una cosita, los polyfills. Es bastante sencillo, pero no me explique bien el dia de la presentacion y lo que explique resulta que tuve un error, si quieres ver un poco mas esta la discusion en el canal de [soporte](https://discord.com/channels/883483443936235530/1203862214726123561). 

En fin, tienes que crear un archivo `src/polyfills.ts` con el siguiente contenido:

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { } };  
```

Y tienes que decirle a Nx que quieres que use esos polyfills. Para eso tienes que:

- Agregar una referencia al archivo "./src/polyfills.ts" en el archivo [project.json](https://github.com/robertohuertasm/solana-bootcamp/blob/main/project.json#L18) al final del arreglo en `targets.build.options.polyfills`.
- Agregar una referencia al archivo "./src/polyfills.ts" en el archivo [tsconfig.app.json](https://github.com/robertohuertasm/solana-bootcamp/blob/main/tsconfig.app.json#L7) al final del arreglo en `files`.

**Comment by robertohuertasm** [comment]
Los metí directamente en el `main.ts`. ¿Es necesario todo el tema de crear un fichero especial y demás? Pensaba que siendo `main` el entry point y declarando esto a nivel global, tal y como estamos haciendo, ya sería suficiente.

**Comment by robertohuertasm** [comment]
He hecho los cambios por si acaso, pero me gustaría entender por qué se necesita hacer de esta manera. Saludos!

**Comment by danmt** [comment]
Tienes toda la razón agregarlo en el `main.ts` tambien funciona. No vi el archivo polyfills y asumi que faltaba, mi error totalmente. Yo recomiendo tenerlo en un archivo separado para no confundirlos y asi mantener los polyfills por separado. 

Ojo, no me extrañaria que Nx haga algun truquito adicional con el bundler y que haga algun tipo de procesamiento si se agrega en los polyfills. Esa parte si que no te podria dar un 100% de certeza, lo que si te puedo asegurar es que yo lo hago asi mas por costumbre que por otra cosa.

**Comment by robertohuertasm** [comment]
Gracias por la aclaración @danmt!
